import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Me from "./components/Me";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fidelis Karuri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center md:flex-row md:flex p-4 md:pt-12 md:p-16  ">
        <Me />
        <main className="flex-1 md:h-full w-full px-16 ">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
